services:
  sonarqube:
    image: sonarqube:26.8.0.126808-community
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://127.0.0.1:9000/api/system/status | grep --quiet '\"status\":\"UP\"'",
        ]
      interval: 5s
      timeout: 5s
      retries: 60
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
