pub const PublicError = enum {
    ENGINE_CONFIG_READ_ERROR,
    ENGINE_CONFIG_PARSE_ERROR,
    LLM_PROVIDER_CONFIG_READ_ERROR,
    LLM_PROVIDER_CONFIG_PARSE_ERROR,
    LLM_PROVIDER_REGISTRY_INVALID,
    LLM_PROVIDER_MODEL_BINDING_INVALID,
    LOGGING_POLICY_INVALID,
    WORKFLOW_AUTHORITY_INVENTORY_INVALID,
    WORKFLOW_DEFINITION_READ_ERROR,
    WORKFLOW_DEFINITION_PARSE_ERROR,
    WORKFLOW_DEFINITION_SCHEMA_INVALID,
    WORKFLOW_GRAPH_COMPILE_INVALID,
    WORKFLOW_REGISTRY_INVALID,
    BOOTSTRAP_ROOT_RESOLUTION_ERROR,
    BOOTSTRAP_ROOT_REGISTRY_INVALID,
    TOOLCHAIN_INVALID,

    pub fn text(self: PublicError) []const u8 {
        return @tagName(self);
    }
};
